### ISSUE TITLE
List requirements

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cdt-builds#32]
It would be good to have a list of requirements somewhere to simplify creating or updating an environment to run the scripts here.

**Comment by beckermr** [comment]
Ugh sorry! Yes, it would be! 

For now, you can look here

https://github.com/conda-forge/cdt-builds/blob/master/.ci_scripts/install_miniconda.sh#L16

**Comment by jakirkham** [comment]
Thanks! That's already quite helpful 🙂

**Comment by jakirkham** [comment]
Tried to refactor that list out into an environment file in PR ( https://github.com/conda-forge/cdt-builds/pull/34 ). Please let me know what you think 🙂

**Comment by beckermr** [comment]
Thank you!

**Comment by jakirkham** [comment]
Of course 😄
