### ISSUE TITLE
libudev for cos7

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/cdt-builds#41]
Is there any reason why this CDT is in "custom-cdt"

https://github.com/conda-forge/cdt-builds/blob/5b1ebbacdf2e715e1dedf49f17a12b1c766c2476/custom_cdts/libudev-devel-cos6-x86_64/meta.yaml#L2

Can we move it out of there? It is needed for libusb https://github.com/conda-forge/libusb-feedstock/pull/6

**Comment by beckermr** [comment]
I don't follow what the issue is.

**Comment by hmaarrfk** [comment]
i guess then i don't understand why libudev wasn't built for cos7. Is it incompatible?

**Comment by beckermr** [comment]
I only built the CDTs needed at the time when we migrated from feedstocks to building them all in this repo. If we need more, we should add them.

**Comment by hmaarrfk** [comment]
great! got it.

**Comment by hmaarrfk** [comment]
I guess i ran into https://github.com/conda-forge/cdt-builds/issues/40 when I tried to make the PR last night.

**Comment by hmaarrfk** [comment]
Is it as simply as copy pasting the files and adjusting them as needed?

**Comment by mbargull** [comment]
`libudev-devel` is provided by `systemd-devel` in CentOS 7. You could do something like
```yaml
- {{ cdt('libudev-devel') }}  # [cdt_name=='cos6']
- {{ cdt('systemd-devel') }}  # [cdt_name=='cos7']
```

**Comment by ryanvolz** [comment]
> `libudev-devel` is provided by `systemd-devel` in CentOS 7. You could do something like
> 
> ```yaml
> - {{ cdt('libudev-devel') }}  # [cdt_name=='cos6']
> - {{ cdt('systemd-devel') }}  # [cdt_name=='cos7']
> ```

Using this suggestion works for `libusb` and I'd imagine is the way to go for any other packages that might be affected. I think this can be closed.
