### ISSUE TITLE
Start building `.conda` artefacts

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/cdt-builds#73]
This feedstock is one of the places (perhaps the last? 🤔) that we missed for https://github.com/conda-forge/conda-forge.github.io/issues/1586

**Comment by beckermr** [comment]
Wait, I thought the default in conda-build changed to `.conda`? Did that not happen or do we have an old pin lying around?

**Comment by beckermr** [comment]
The default never changed. 🤦

**Comment by h-vetinari** [comment]
> The default never changed. 🤦

It's still planned, but hasn't happened yet: https://github.com/conda/conda-build/issues/5183
